apiVersion: v2
name: indian-job-search
description: Multi-Agent Job Search for Indian Market with Azure AI Integration
type: application
version: 1.0.0
appVersion: "1.0.0"
keywords:
  - job-search
  - india
  - ai
  - azure
  - kubernetes
  - airflow
home: https://github.com/varunbiluri/indian-job-search-agents
sources:
  - https://github.com/varunbiluri/indian-job-search-agents
maintainers:
  - name: varun
    email: varunreddy.billuri@gmail.com
icon: https://img.icons8.com/color/96/000000/india.png
