# Default values for Indian Job Search Application
# This is a YAML-formatted file.

# Application Configuration
app:
  name: indian-job-search
  version: "1.0.0"
  environment: production
  replicas: 3

# Image Configuration
image:
  repository: job-search-api
  tag: "latest"
  pullPolicy: IfNotPresent

# Azure AI Configuration
azure:
  openai:
    enabled: true
    endpoint: "https://your-resource.openai.azure.com"
    deployment_name: "gpt-4"
    api_version: "2024-02-15-preview"
  cognitive:
    enabled: true
    endpoint: "https://your-resource.cognitiveservices.azure.com"
  ml:
    enabled: true
    endpoint: "https://your-workspace.azureml.net"

# AI Models Configuration
aiModels:
  enabled: true
  llama2:
    enabled: true
    replicas: 2
    resources:
      requests:
        memory: "1Gi"
        cpu: "500m"
      limits:
        memory: "2Gi"
        cpu: "1000m"
  falcon:
    enabled: true
    replicas: 2
    resources:
      requests:
        memory: "1Gi"
        cpu: "500m"
      limits:
        memory: "2Gi"
        cpu: "1000m"
  mistral:
    enabled: true
    replicas: 2
    resources:
      requests:
        memory: "1Gi"
        cpu: "500m"
      limits:
        memory: "2Gi"
        cpu: "1000m"

# Airflow Configuration
airflow:
  enabled: true
  dags:
    - name: indian_job_search_automation
      schedule: "0 * * * *"  # Every hour
      enabled: true
  webserver:
    replicas: 2
    resources:
      requests:
        memory: "512Mi"
        cpu: "250m"
      limits:
        memory: "1Gi"
        cpu: "500m"
  scheduler:
    replicas: 2
    resources:
      requests:
        memory: "512Mi"
        cpu: "250m"
      limits:
        memory: "1Gi"
        cpu: "500m"

# Database Configuration
database:
  type: postgresql
  host: airflow-postgresql
  port: 5432
  name: airflow
  user: airflow
  password: airflow

# Redis Configuration
redis:
  enabled: true
  host: redis
  port: 6379

# Service Configuration
service:
  type: LoadBalancer
  port: 80
  targetPort: 8000
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-health-probe-request-path: /health

# Ingress Configuration
ingress:
  enabled: false
  className: nginx
  annotations:
    kubernetes.io/ingress.class: nginx
  hosts:
    - host: indian-job-search.local
      paths:
        - path: /
          pathType: Prefix

# Resources Configuration
resources:
  requests:
    memory: "512Mi"
    cpu: "250m"
  limits:
    memory: "1Gi"
    cpu: "500m"

# Autoscaling Configuration
autoscaling:
  enabled: true
  minReplicas: 3
  maxReplicas: 10
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 80

# Security Configuration
security:
  runAsNonRoot: true
  runAsUser: 1000
  fsGroup: 1000
  capabilities:
    drop:
      - ALL

# Monitoring Configuration
monitoring:
  enabled: true
  prometheus:
    enabled: true
    port: 9090
  grafana:
    enabled: false

# Backup Configuration
backup:
  enabled: true
  schedule: "0 2 * * *"  # Daily at 2 AM
  retention: 7  # Keep 7 days of backups

# Environment Variables
env:
  - name: NODE_ENV
    value: "production"
  - name: LOG_LEVEL
    value: "INFO"
  - name: INDIA_MARKET_ENABLED
    value: "true"
