apiVersion: apps/v1
kind: Deployment
metadata:
  name: indian-job-search-web
  namespace: varun-dev
  labels:
    app: indian-job-search-web
    version: "2.0.0"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: indian-job-search-web
  template:
    metadata:
      labels:
        app: indian-job-search-web
    spec:
      containers:
        - name: web-app
          image: python:3.11-slim
          ports:
            - containerPort: 8000
          env:
            - name: PYTHONPATH
              value: "/app"
            - name: PYTHONUNBUFFERED
              value: "1"
            - name: BRANCH
              value: "001/jenkins-test"
          command: ["/bin/bash"]
          args:
            - -c
            - |
              apt-get update && apt-get install -y gcc curl
              pip install fastapi==0.104.1 uvicorn[standard]==0.24.0 pydantic==2.5.0
              mkdir -p /app/src/web
              cat > /app/src/web/main.py << 'INNER_EOF'
              from fastapi import FastAPI, Query
              from fastapi.responses import HTMLResponse
              from typing import List, Optional, Dict
              from datetime import datetime, timedelta
              import uvicorn
              
              app = FastAPI(title="Indian Job Search Agents", version="2.0.0")
              
              MOCK_JOBS = [
                  {
                      "job_id": "JS001",
                      "title": "Senior Python Developer",
                      "company": "TechCorp India",
                      "location": "Bangalore, India",
                      "description": "Senior Python Developer with FastAPI, Django expertise.",
                      "requirements": ["Python", "FastAPI", "Django", "AWS", "5+ years"],
                      "salary_range": "₹15-25 LPA",
                      "contact_info": {"email": "hr@techcorp.in", "phone": "+91-98765-43210"},
                      "confidence_score": 0.95,
                      "source": "Company Website",
                      "posted_date": datetime.now() - timedelta(days=2)
                  },
                  {
                      "job_id": "JS002",
                      "title": "AI/ML Engineer",
                      "company": "StartupXYZ",
                      "location": "Mumbai, India",
                      "description": "Build cutting-edge ML models for Indian market.",
                      "requirements": ["Python", "TensorFlow", "PyTorch", "NLP", "3+ years"],
                      "salary_range": "₹12-20 LPA",
                      "contact_info": {"email": "careers@startupxyz.com", "phone": "+91-98765-12345"},
                      "confidence_score": 0.92,
                      "source": "LinkedIn",
                      "posted_date": datetime.now() - timedelta(days=1)
                  }
              ]
              
              @app.get("/", response_class=HTMLResponse)
              async def home():
                  return HTMLResponse(content="""
                  <!DOCTYPE html>
                  <html>
                  <head>
                      <title>Indian Job Search Agents - AI-Powered Job Search</title>
                      <script src="https://cdn.tailwindcss.com"></script>
                      <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css" rel="stylesheet">
                  </head>
                  <body class="bg-gradient-to-br from-blue-50 to-indigo-100 min-h-screen">
                      <header class="bg-white shadow-lg">
                          <div class="max-w-7xl mx-auto px-4 py-6">
                              <div class="flex items-center">
                                  <i class="fas fa-search text-3xl text-indigo-600 mr-3"></i>
                                  <h1 class="text-3xl font-bold text-gray-900">Indian Job Search Agents</h1>
                              </div>
                          </div>
                      </header>
                      
                      <main class="max-w-7xl mx-auto px-8 py-12">
                          <div class="text-center mb-16">
                              <h2 class="text-5xl font-bold text-gray-900 mb-6">AI-Powered Job Search for India</h2>
                              <p class="text-xl text-gray-600 mb-8">Discover opportunities across Indian startups using AI agents.</p>
                              <div class="flex justify-center space-x-4">
                                  <a href="/api/jobs" class="bg-indigo-600 text-white px-8 py-4 rounded-lg text-lg font-semibold hover:bg-indigo-700">View Jobs</a>
                                  <a href="/docs" class="bg-green-600 text-white px-8 py-4 rounded-lg text-lg font-semibold hover:bg-green-700">API Docs</a>
                              </div>
                          </div>
                          
                          <div class="bg-white rounded-xl shadow-lg p-8">
                              <h3 class="text-2xl font-bold mb-6">Recent Job Postings</h3>
                              <div id="jobs" class="space-y-4"></div>
                          </div>
                      </main>
                      
                      <script>
                          fetch('/api/jobs')
                              .then(response => response.json())
                              .then(jobs => {
                                  const jobsContainer = document.getElementById('jobs');
                                  jobsContainer.innerHTML = jobs.map(job => `
                                      <div class="border-l-4 border-indigo-500 pl-4 py-3">
                                          <h4 class="font-semibold text-lg">${job.title}</h4>
                                          <p class="text-gray-600">${job.company} • ${job.location}</p>
                                          <p class="text-sm text-gray-500">${job.salary_range} • Posted ${new Date(job.posted_date).toLocaleDateString()}</div>
                                      </div>
                                  `).join('');
                              });
                      </script>
                  </body>
                  </html>
                  """)
              
              @app.get("/api/jobs")
              async def get_jobs():
                  return MOCK_JOBS
              
              @app.get("/health")
              async def health():
                  return {"status": "healthy", "version": "2.0.0", "branch": "001/jenkins-test"}
              
              if __name__ == "__main__":
                  uvicorn.run(app, host="0.0.0.0", port=8000)
              INNER_EOF
              cd /app && python -m uvicorn src.web.main:app --host 0.0.0.0 --port 8000
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: indian-job-search-web
  namespace: varun-dev
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8000
      protocol: TCP
  selector:
    app: indian-job-search-web
