apiVersion: apps/v1
kind: Deployment
metadata:
  name: job-search-api
  namespace: varun-dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: job-search-api
  template:
    metadata:
      labels:
        app: job-search-api
    spec:
      containers:
        - name: api
          image: job-search-api:latest
          ports:
            - containerPort: 8000
          env:
            - name: DATABASE_URL
              value: "postgresql://airflow:airflow@airflow-postgresql:5432/airflow"
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: openai-secret
                  key: api-key
            - name: REDIS_URL
              value: "redis://redis:6379"
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "1Gi"
              cpu: "1000m"
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: job-search-api
  namespace: varun-dev
spec:
  type: ClusterIP
  ports:
    - port: 8000
      targetPort: 8000
  selector:
    app: job-search-api
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: job-search-api-hpa
  namespace: varun-dev
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: job-search-api
  minReplicas: 2
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80
