apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "indian-job-search.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "indian-job-search.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.app.replicas }}
  selector:
    matchLabels:
      {{- include "indian-job-search.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "indian-job-search.selectorLabels" . | nindent 8 }}
    spec:
      {{- if .Values.security.runAsNonRoot }}
      securityContext:
        runAsNonRoot: {{ .Values.security.runAsNonRoot }}
        runAsUser: {{ .Values.security.runAsUser }}
        fsGroup: {{ .Values.security.fsGroup }}
        capabilities:
          {{- toYaml .Values.security.capabilities | nindent 6 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.targetPort }}
              protocol: TCP
          env:
            - name: DATABASE_URL
              value: "postgresql://{{ .Values.database.user }}:{{ .Values.database.password }}@{{ .Values.database.host }}:{{ .Values.database.port }}/{{ .Values.database.name }}"
            - name: REDIS_URL
              value: "redis://{{ .Values.redis.host }}:{{ .Values.redis.port }}"
            - name: AZURE_OPENAI_ENDPOINT
              value: {{ .Values.azure.openai.endpoint | quote }}
            - name: AZURE_OPENAI_DEPLOYMENT
              value: {{ .Values.azure.openai.deployment_name | quote }}
            - name: INDIA_MARKET_ENABLED
              value: "true"
            {{- range .Values.env }}
            - name: {{ .name }}
              value: {{ .value | quote }}
            {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
